"""empty message

Revision ID: 88893190c2cc
Revises: 8ab18bc0038f
Create Date: 2020-09-10 23:17:13.364398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88893190c2cc'
down_revision = '8ab18bc0038f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('industry', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
